name: yarn

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependecies
      run: yarn
    - name: Run lint script
      run: yarn lint
